# Generated by Django 4.0.3 on 2022-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('hospitalname', models.CharField(max_length=200)),
                ('fee', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
