# Generated by Django 4.0.3 on 2022-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_doctors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
    ]
