# Generated by Django 4.0.3 on 2022-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='email',
            field=models.EmailField(default='yellumahanthysaipavan@gmail.com', max_length=254),
        ),
    ]
