# Generated by Django 4.0.3 on 2022-09-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='email',
            field=models.EmailField(default='govardhansathvik83@gmail.com', max_length=254),
        ),
    ]
