# Generated by Django 4.0.3 on 2022-09-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_blood_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Date_of_appointment', models.DateField()),
                ('Docname', models.CharField(max_length=100)),
            ],
        ),
    ]
